project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Fortgeschrittene quantitative Methoden"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Daria Tisch"
    background: "#D92609"

  sidebar:
    background: "#D92609"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dariatisch/wup2024
        text: GitHub
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Course information"
      - section: "Schedule"
        contents:
          - href: schedule.qmd
            text: Schedule
          - href: slides/1_uebung.qmd
            text: "Übung 01"
    	

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
