project:
  type: website
  output-dir: docs

website:
  title: "Fortgeschrittene quantitative Methoden"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dariatisch/wup2024
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule
      - text: Materials
        menu:
          - href: materials.qmd
            text: Overview
          - href: slides/week1.html
            text: Week 1 Slides
          - href: slides/week2.html
            text: Week 2 Slides
          - href: 01_uebung.qmd
            text: Sitzung01

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

