project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Fortgeschrittene quantitative Methoden"
  sidebar:
    background: "#D9E3E4"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dariatisch/wup2024
        text: GitHub
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Course information"
      - section: "Schedule"
        contents:
          - href: schedule.qmd
            text: Schedule
          - href: slides/1_uebung.qmd
            text: bung1
    	

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
