project:
  type: website
  output-dir: docs

website:

  title: "Fortgeschrittene quantitative Methoden"
  sidebar:
    background: "#D9E3E4"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dariatisch/wup2024
        text: GitHub
    style: docked


format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto
