project:
  render:
    - "*.qmd"
    - "!/downloads"
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Fortgeschrittene quantitative Methoden"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Daria Tisch"
    background: "#20a1a1"

  sidebar:
    background: "#20a1a1"
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/dariatisch/wup2024
        text: GitHub
    style: docked
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Kursinformationen"
      - section: "Zeitplan und Dateien"
        contents:
          - href: schedule.qmd
            text: Übersicht
          - href: slides/1_uebung.qmd
            text: "1 - Übung"
          - href: slides/1_seminar.qmd
            text: "1 - Seminar"
          - href: uebungen/1_uebungsblatt.qmd
            text: "1 - Übungsblatt"   	

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true


execute:
  freeze: auto

